<?php

namespace AppBundle\Repository;

/**
 * HeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeatRepository extends \Doctrine\ORM\EntityRepository
{
}
